DMApp/DMApp/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^managing/', include('managing.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^donate/', include('donate.urls')),
    url(r'^$', include('donate.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DMApp/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
   url(r'^signup/$', views.signup_view, name="signup"),
   url(r'^login/$', views.login_view, name="login"),
   url(r'^logout/$', views.logout_view, name="logout"),
]   

DMApp/donate/urls.py
from django.conf.urls import url
from . import views

app_name = 'donate'

urlpatterns = [
   url(r'^home/', views.donate, name="donate"),
   url(r'^help/', views.help, name="help"),
   url(r'^challan/', views.challan, name="challan"),
   url(r'^$', views.home, name="home"),
   url(r'^manual', views.man, name="man"),
   url(r'^about', views.about, name="about"),
]   

DMApp/managing/urls.py
from django.conf.urls import url
from . import views 

app_name = 'managing'

urlpatterns = [
    url(r'^$', views.victim_list, name="list"),
    url(r'^enter/$', views.victim_new, name="enter"),
    url(r'^applist/$', views.app_victimlist, name="applist")
]

DMApp/accounts/models.py
from django.db import models

# Create your models here.

DMApp/donate/models.py
from django.db import models
from django.contrib.auth.models import User

class Donor(models.Model):
	name = models.CharField(max_length=50)
	amount = models.PositiveIntegerField(default=100)
	date = models.DateTimeField(auto_now_add=True)

DMApp/managing/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
GENDER_CHOICES = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
)

STATUS = (
    ('recovering', 'Recovering'),
    ('critical', 'Critical'),
    ('died', 'Died'),
)
    

class Victim(models.Model):
    name = models.CharField(max_length=50, blank=True)
    age = models.PositiveIntegerField(default=21, blank=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default='Male', blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='Recovering')
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg')
    hospital_address = models.TextField(default='Add Hospital/Relief Camp Address', blank=False)
    admitter = models.ForeignKey(User, default=1, blank=False, on_delete=models.CASCADE)
    

    def __str__(self):
        return '{ name:"' + self.name + '",age:"' + str(self.age) + '",gender:"'+self.gender + '",status:"'+self.status + '",location:"' + self.hospital_address + '",admitter:"'+ str(self.admitter) +'",image:"'+self.thumb.url + '"}'

DMApp/donate/forms.py
from django import forms
from . import models

class DonorForm(forms.ModelForm):
    class Meta:
        model = models.Donor
        fields = ['name', 'amount']

DMApp/managing/forms.py
from django import forms
from . import models

class VictimForm(forms.ModelForm):
    class Meta:
        model = models.Victim
        fields = ['name', 'age', 'gender', 'status', 'hospital_address', 'thumb']

DMApp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('managing:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_page.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 's@next' in request.POST:
                return redirect(request.POST.get('s@next'))
            else:
                return redirect('managing:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login_page.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('managing:list')

DMApp/donate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from . import forms

from django.views.generic import View
from django.utils import timezone
from .render import Render
from datetime import datetime
import re

text = ''
# Create your views here.

def donate(request):
    template = loader.get_template('donate/donate.html')
    context = {}
    return HttpResponse(template.render(context, request))

def home(request):
    template = loader.get_template('donate/home.html')
    context = {}
    return HttpResponse(template.render(context, request))

def challan(request):
    if request.method == 'POST':
        nm = request.POST.get('name')
        amt = request.POST.get('amount')
        dt = request.POST.get('date')
        
        context = {
            'name':nm,
            'amount':amt,
            'date':dt
        }
        return Render.render('donate/gen.html',{'context':context})
    else:
        form = forms.DonorForm
        return render(request, 'donate/challan.html', {'form':form})

def help(request):
    template = loader.get_template('donate/help.html')
    context = {}
    return HttpResponse(template.render(context, request))

def man(request):
    template = loader.get_template('donate/man.html')
    context = {}
    return HttpResponse(template.render(context, request))

def about(request):
    template = loader.get_template('donate/about.html')
    context = {}
    return HttpResponse(template.render(context, request))

DMApp/managing/views.py
from django.shortcuts import render, redirect
from .models import Victim
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def victim_list(request):
    if request.method=="POST":
        nm = request.POST.get('name')
        victims = Victim.objects.filter(name=nm).order_by('name')
        return render(request, 'managing/victim_list.html', {'victims':victims})
    else:
        victims = Victim.objects.all().order_by('name')
        return render(request, 'managing/victim_list.html', {'victims':victims})

def app_victimlist(request):
    strng = ','.join([str(i) for i in Victim.objects.all().order_by('name').defer('thumb','date')])
    return HttpResponse('[' + strng + ']')

@login_required(login_url="/accounts/login/")
def victim_new(request):
    if request.method == 'POST':
        form = forms.VictimForm(request.POST, request.FILES)
        if form.is_valid():
            s_instance = form.save(commit=False)
            s_instance.admitter = request.user
            s_instance.save()
            return redirect('managing:list')
    else:
        form = forms.VictimForm
    return render(request, 'managing/victim_enter.html', {'form':form})

DMApp/accounts/templates/accounts/login_page.html
{% extends 'base_temp.html' %}

{% block one %}
    <h1 id="detailhead">Log In</h1>
    <form style="color:black" class="login_form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="s@next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Log In">
    </form>
{% endblock %}

DMApp/accounts/templates/accounts/signup_page.html
{% extends 'base_temp.html' %}

{% block one %}
    <h1 id="detailhead">Sign Up </h1>
    <form class="signup_form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

DMApp/donate/templates/donate/about.html
{% extends 'base_temp.html' %}

{% block one %}
<center>
    <h1 id="detailhead">ABOUT US</h1>

<div class="row">
<img class="col-sm-4" style="max-width:20vh;max-height: 20vh" src="https://image.ibb.co/nNBxDA/Whats-App-Image-2018-03-26-at-6-59-03-PM.jpg" alt="Whats-App-Image-2018-03-26-at-6-59-03-PM" border="0">
<p id="details">
    <strong>Name:</strong> Akash Nair
    <br>
    <strong>Email:</strong> akash30121998@gmail.com
</p>

<img class="col-sm-4" style="max-width:20vh;max-height: 20vh" src="https://image.ibb.co/f9KjtA/Whats-App-Image-2018-10-26-at-7-47-21-PM.jpg" alt="Whats-App-Image-2018-10-26-at-7-47-21-PM" border="0">
<p id="details">
        <strong>Name:</strong> Saurabh Agarwala
        <br>
        <strong>Email:</strong> saur.agarwala@gmail.com
    </p>
<img class="col-sm-4" style="max-width:20vh;max-height: 17vh" src="https://image.ibb.co/jBpTLq/Whats-App-Image-2018-10-26-at-7-54-15-PM.jpg" alt="Whats-App-Image-2018-10-26-at-7-54-15-PM" border="0">
<p id="details">
        <strong>Name:</strong> Vaibhav G
        <br>
        <strong>Email:</strong> gvaibhav1734@gmail.com
    </p>
</div>
</center>
{% endblock %}

DMApp/donate/templates/donate/challan.html
{% extends 'base_temp.html' %}

{% block one %}
    <h1 id="detailhead">E-Challan Payment</h1>

    <p id="details">Enter your Full Name and Amount you wish to donate, in order to generate a challan and it may be submitted to your local Bank</p>

    <form action="{% url 'donate:challan' %}" class="ws-validate" method="POST">
    {% csrf_token %}                       
        <div id="detailp" class="form-row">
            Donor Name: {{ form.name }}
        </div>
        <div id="detailp" class="form-row">
            Donation Amount: {{ form.amount }}</div>
        <br>
        <div class="form-row">
            <input class="btn btn-primary" type="submit" />
        </div>
    </form>
        <br>        
{% endblock %}

DMApp/donate/templates/donate/donate.html
{% extends 'base_temp.html' %}

{% block one %}
    <h1 id="detailhead">Donation Page</h1>

    <hr>

    <a id="detailp" href="{% url 'donate:challan' %}">Generate E-Challan Payment</a>
    <br><br>
    <a href="https://media.ifrc.org/ifrc/donate/" id="detailp">Donate for other Causes at RedCrescent</a><br><br>
    <a href="https://www.redcross.org/donate/donation.html/" id="detailp">Donate for other Causes at RedCross</a>

    

{% endblock %}

DMApp/donate/templates/donate/gen.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>E-Challan | {{ context.name }}</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1.5cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }
        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
            border-top: 2px solid #000;
        }
        .table .table {
            background-color: #fff;
        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>E-Challan Payment</h1>
            <h3>Reciever : RMD Foundation for Disaster Relief</h3>
            <h3>Bank Name: RMD DUMMY BANK</h3>
            <h3>Account No of Reciever: $$DUMMYNUMBER$$</h3>
        </div>

        <div class="list-group">
            <p>Name: {{ context.name }}</p>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>Name of Donor</th>
                <th>Donation Amount</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ context.name }}</td>
                    <td>Rs. {{ context.amount }}</td>
                </tr>
            </tbody>
        </table>
        <div class="list-group">
            <p>[To be filled before submitting]</p>
            <p>No. of Two Thousand Rupee Notes: ___________</p>
            <p>No. of Thousand Rupee Notes: ___________</p>
            <p>No. of Hundred Rupee Notes: ___________</p><br>
            <p>Cheque No.: __________________________</p>

        </div>
    </div>
</div>

</body>
</html>

DMApp/donate/templates/donate/help.html
{% extends 'base_temp.html' %}

{% block one %}
<center>
    <h1 id="detailhead">Emergency Contact Numbers</h1>
</center>
<br><br>
<ul class="row" id="details" style="font-size:170%">
    <li class="col-sm-4"><strong>National Emergency Number:</strong><em> 112</em></li>
    <li class="col-sm-4"><strong>Police:</strong><em> 100</em></li>
    <li class="col-sm-4"><strong>Fire:</strong><em> 101</em></li>
    <li class="col-sm-4"><strong>Ambulance:</strong> <em>102</em></li>
    <li class="col-sm-4"><strong>Disaster Managemnt Services:</strong> <em>108</em></li>
    <li class="col-sm-4"><strong>Women Helpline:</strong><em> 1091</em></li>
    <li class="col-sm-4"><strong>Air Ambulance:</strong> <em>9540161344</em></li>
    <li class="col-sm-4"><strong>Earthquake/Flood/Disaster:</strong><em> 011-24363260</em></li>
    <li class="col-sm-4"><strong>Disaster Distress Helpline:</strong> <em>180098559990</em></li>
</ul>

<p id="detailp"><a href="http://indianhelpline.com/">Visit Here for More Numbers!</a></p>

{% endblock %}

DMApp/donate/templates/donate/home.html
{% extends 'base_temp.html' %}

{% block one %}
<center>
    <h1 id="detailhead">RMD Home</h1>
</center>

<p id="details" style="font-size:170%">
        This Web App focuses on the relief organizations and Hospitals who can use the application to record Victim details, help users with donation process, provide details on survival manuals and Emergency Contact Numbers
<br>
        The Android App focuses on the users and victims of natural disasters to locate themselves on an offline map of the region, SOS feature that allows them to contact a pre determined contact  and sends their current location as part of a message.
        Along with these key features, it also provides details on survival manuals and Emergency Contact Numbers.
</p>

{% endblock %}

DMApp/donate/templates/donate/man.html
{% extends 'base_temp.html' %}

{% block one %}
<center>    
<h1 id="detailhead">Help Manuals</h1>
</center>

<div id="detailp" id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                Earthquake
              </button>
            </h5>
          </div>
      
          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                <img src="http://infographicimages.com/infographics/earthquake-tips.jpg" alt="EARTHQUAKE">
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Flood Safety Guide
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                    <img src="https://i.pinimg.com/564x/bd/04/53/bd0453af166e0bc99fca14355d35321b.jpg" alt="FLOOD">
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Tips on CPR
              </button>
            </h5>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
                    <img src="https://i.pinimg.com/564x/b1/0f/44/b10f44ae38e091a68f875b5a437a6492.jpg" alt="CPR">
                                </div>
          </div>
          <div class="card">
                <div class="card-header" id="headingFour">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                      Hypothermia Tips
                    </button>
                  </h5>
                </div>
            
                <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
                  <div class="card-body">
                      <img src="https://i.pinimg.com/564x/c5/fd/44/c5fd44054bb271e7175bfb7d623a2fce.jpg" alt="HYPOTHERMIA">
                  </div>
                </div>
              </div>
        </div>
        <div class="card">
                <div class="card-header" id="headingFive">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFour">
                      Tornado
                    </button>
                  </h5>
                </div>
            
                <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
                  <div class="card-body">
                      <img src="https://i.pinimg.com/564x/e9/5b/e0/e95be086b73fd11638332d7852bd1ed2.jpg" alt="TORNADO">
                  </div>
                </div>
              </div>
        </div>
      </div>

{% endblock %}

DMApp/managing/templates/managing/victim_enter.html
{% extends 'base_temp.html' %}

{% block one %}
    <div class="enter_victim">
        <h1 id="detailhead">Enter Details of Victim</h1>
        <form style="color:black" class="enter_victim_form" action="{% url 'managing:enter' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save Victim Details">
        </form>
    </div>
{% endblock %}

DMApp/managing/templates/managing/victim_list.html
{% extends 'base_temp.html' %}

{% block one %}
	<form action="{% url 'managing:list' %}" class="ws-validate" method="POST">
		{% csrf_token %}                       
	<div class="form-row">
		<p id="detailp" style="display:inline-block">Search: </p>
		<input type="text" class="hide-replaced" name="name"/>
	</div>
	<br>
	<div class="form-row">
		<input class="btn btn-primary" type="submit" />
	</div>
	</form>
	<br>
	{% if victims %}<center>
	<h1 id="detailhead">Victim List</h1>
    <div class="row" style="align-self:center;width: 100%">
		{% for victim in victims %}
		<div class="col-lg-4" style="color:rgb(0, 0, 0); background-color:rgb(255, 255, 255)">
			<img src="{{ victim.thumb.url }}" style="max-width:25vh; max-height: 20vh">
			<h4>Name: {{ victim.name }}<br>
				Age: {{ victim.age }}	<br>Gender: {{ victim.gender }}<br>
				Status: {{ victim.status }}<br>
				Present In: {{ victim.admitter }} <br>
				Address: {{ victim.hospital_address }}
			</h4>
            <p>Entry Made On: {{ victim.date }}</p></div>
        {% endfor %}
    </div></center>
	{% else %}
	<h3>Sorry the entered name doesn't match any of the entries.</h3>
	{% endif %}
{% endblock %}